using Godot;
using System;
using System.Collections.Generic;

/*
    This system is a piece of crap adhered to the wall with masking tape and a prayer.
*/
public partial class CelestialBody : Node3D
{
    public Configuration Config { get; private set; }
    
    // Stuff generated by the planet itself
    public OrbitDriver OrbitDriver { get; private set; }
    public TerrainGen TerrainSphere { get; private set; }
    public TerrainGen OceanSphere { get; private set; }
    public ScaledObject ScaledObject { get; private set; }
    public MapObject MapObject { get; private set; }
    public List<CelestialBody> OrbitingCBodies { get; private set; } = [];

    // Misc
    public Vector3 AbsolutePosition { get; private set; } // Precision degrades with this, so perhaps find a way to circumvent this
    public Transform3D AbsoluteTransform { get; private set; } // The absolute transform (basis), irrespective of reference frames
    public double Rot { get; private set; }
    public Node3D Pivot { get; private set; }
    public Node3D Gimbal { get; private set; }

    // Struct for storing all necessary creation info in one place (to avoid clutter)
    public struct Configuration
    {
        public bool isRootBody;
        public Properties properties;
        public Rotation rotation;
        public Light light;
        public KeplerianState.KeplerianElements orbitElements;
        public string parentCBodyName; // Reluctantly use name since celestial bodies might not be instantiated
        public TerrainGen.Properties terrainProperties;

        public struct Properties
        {
            public string name;
            public bool focusOnLoad;
            public double geeASL;
            public double mass;
            public double radius;
            public double inverseRotAltitude;
            public double sphereOfInfluence;
        }
        public struct Rotation
        {
            public double initial;
            public double period;
            public Vector3 tilt;
        }
        public struct Light
        {
            public float brightness;
            public Color colour;
        }
    }

    public void Update()
    {
        if (OrbitDriver != null)
        {
            ProcessTransform();
        }
    }

    // Process the cBody positioning / rotation calculations.
    public void ProcessTransform()
    {
        // Godot automatically transforms the rotation and sometimes planets can end up being titled to some baffling degree so just do this and forget
        Rotation = Vector3.Zero;

        if (OrbitDriver.Enabled)
        {
            OrbitDriver.Update();
            AbsolutePosition = OrbitDriver.CartState.elements.position + OrbitDriver.ParentCBody.OrbitDriver.CartState.elements.position;
        }else{
            AbsolutePosition = Vector3.Zero;
        }

        Vector3 originPos;
        // Uh
        if (RealityTangler.Instance.RotatingReferenceFrame == this)
        {
            originPos = AbsolutePosition - RealityTangler.Instance.OriginOffset; 
        }else{
            originPos = AbsolutePosition - RealityTangler.Instance.PlanetaryOffset;
        }

        // Process position, then the scaled and map object's positions
        Position = originPos;
        ScaledObject.truePosition = GlobalPosition;

        MapObject.truePosition = AbsolutePosition;
        MapObject.Rotation = AbsoluteTransform.Basis.GetEuler();

        // Update rotation
        Rot = Config.rotation.initial + Math.Tau * (ActiveSave.Instance.SaveTime / Config.rotation.period);

        Transform3D trans = new()
        {
            Basis = Basis.FromEuler(new Vector3(0, Rot, 0))
        };

        // Update cached trash
        Transform3D newCachedTransform = new()
        {
            Basis = Pivot.Transform.Basis * trans.Basis
        };
        AbsoluteTransform = newCachedTransform;

        // Don't rotate if this is the active rotating reference frame (the universe is doing the rotation for us)
        if (RealityTangler.Instance.RotatingReferenceFrame != this)
        {
            Gimbal.Transform = trans;
            ScaledObject.Rotation = Gimbal.GlobalTransform.Basis.GetEuler();
        }else{
            Gimbal.GlobalRotation = Vector3.Zero;
            ScaledObject.Rotation = Vector3.Zero;
        }
    }

    public void SetConfiguration(Configuration properties)
    {
        // Compute mass / geeASL depending on what we have in store
        if (properties.properties.mass < 0)
        {
            properties.properties.mass = properties.properties.geeASL * Conics.EarthGravity * Mathf.Pow(properties.properties.radius, 2f) / Conics.GravConstant;
        }
        if (properties.properties.geeASL < 0)
        {
            properties.properties.geeASL = properties.properties.mass * Conics.GravConstant / Mathf.Pow(properties.properties.radius, 2f) / Conics.EarthGravity;
        }

        Config = properties;
    }

    // Set the info first
    public void Instantiate()
    {
        // Locate parent body (this assumes that the desired parent exists)
        CelestialBody parentCBody = CelestialBodyManager.Instance.GetCBodyFromName(Config.parentCBodyName);

        // Initialize orbit driver
        OrbitDriver = new();
        OrbitDriver.Init(parentCBody, this, true);
        OrbitDriver.KeplerState.elements = Config.orbitElements;
        if (parentCBody != null) OrbitDriver.Enabled = true;

        // Add self to the parent's list and the global list
        parentCBody?.OrbitingCBodies.Add(this);
        //CelestialBodyManager.Instance.CelestialBodies.Add(this);

        // Just add it to the manager ig
        CelestialBodyManager.Instance.AddChild(this); 

        // Create physical part
        // Gimbals and pivots for axial tilt and all that other jazz
        Pivot = new();
        AddChild(Pivot);
        Pivot.RotationDegrees = Config.rotation.tilt;
        Pivot.Name = "Pivot";

        Gimbal = new();
        Pivot.AddChild(Gimbal);
        Gimbal.Name = "Gimbal";

        TerrainSphere = new();
        TerrainSphere.Init(Config.terrainProperties, this);

        // Create map and scaled objects
        ScaledObject = new() { Name = $"{Config.properties.name}_Scaled" };
        ScaledSpace.Instance.AddChild(ScaledObject);

        MapObject = MapView.Instance.AddMapObject(Name);
        MapView.Instance.AddMapIcon(MapObject);

        // Add lights
        if (Config.light.brightness > 0)
        {
            CBodyLight cBodyLight = LightingManager.Instance.CreateLight(this);
            cBodyLight.brightness = Config.light.brightness;
            cBodyLight.colour = Config.light.colour;
        }
 
        // Add to the orbit process
        RealityTangler.Instance.OrbitProcess += Update;
    }

    public void ResetOrigin()
    {
        // Just to prevent jitter
        ProcessTransform();
    }

    // Gets the absolute position of a point on the planet (factoring in rotation)
    public Vector3 GetAbsolutePositionOfPoint(Vector3 point)
    {
        return AbsoluteTransform * point;
    }

    public Vector3 GetLocalPositionOfPoint(Vector3 point)
    {
        return AbsoluteTransform.Inverse() * point;
    }

    // Returns the velocity vector of the planet's surface at that point IN THE GEOCENTRIC REFERENCE FRAME!!
    // Ate a bit of https://en.wikipedia.org/wiki/Rigid_body_dynamics and shat out this function
    public Vector3 GetSurfaceRotationVelocity(Vector3 point, bool geocentric = false)
    {
        Vector3 velocity = GetAngularVelocity(geocentric).Cross(point); // Cross and pray

        return velocity;
    }

    public Vector3 GetCoriolisAcceleration(Vector3 velocity, bool geocentric = false)
    {
        return -2 * GetAngularVelocity(geocentric).Cross(velocity);
    }

    public Vector3 GetCentrifugalAcceleration(Vector3 position, bool geocentric = false)
    {
        return -GetAngularVelocity(geocentric).Cross(GetSurfaceRotationVelocity(position));
    }

    public Vector3 GetAngularVelocity(bool geocentric = false)
    {
        // Rotation period is in seconds per 2pi radians.
        // Angular velocity has to be in radians per second.
        double angularVelocity = Math.Tau / Config.rotation.period;

        Vector3 planetUp = Vector3.Up;
        // Factor in planet's tilt if it's not geocentric
        if (!geocentric) planetUp = AbsoluteTransform.Basis.Y;

        Vector3 angularVelocityVector = planetUp * angularVelocity;

        return angularVelocityVector;
    }

    // Returns a local velocity from an absolute velocty
    public Vector3 GetLocalVelocity(Vector3 velocity)
    {
        Vector3 localVel = AbsoluteTransform.Basis.Inverse() * velocity;
        return localVel;
    }

    // Returns an absolute velocity (intertial non-rotating)
    public Vector3 GetAbsoluteVelocity(Vector3 velocity)
    {
        Vector3 globalVel = AbsoluteTransform.Basis * velocity;
        return globalVel;
    }

    // Shamelessly stolen from https://stackoverflow.com/questions/46247499/vector3-to-latitude-longitude
    // CONVERT POSITION TO GEOCENTRIC REFERENCE FRAME FIRST!
    public Vector2 GetLatitudeLongitude(Vector3 position, bool radians = false)
    {
        double lat = Math.Acos(position.Y / Config.properties.radius); //theta
        double lon = Math.Atan(position.X / position.Z); //phi

        // Skip conversion if we just want radians
        if (radians) return new Vector2(lat, lon);

        double radToDeg = 180 / Math.PI;
        return new Vector2(lat * radToDeg, lon * radToDeg);
    }

    public override string ToString()
    {
        return Config.properties.name;
    }
}
